--- #YAML:1.0
name:               App-Bitly
version:            2010082001
abstract:           Shorten URL using the bitly service.
author:
    - Abigail <cpan@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    LWP::Simple:          0
    strict:               0
    Test::More:           0.88
    warnings:             0
build_requires:
    ExtUtils::MakeMaker:  0
    LWP::Simple:          0
    strict:               0
    Test::More:           0.88
    warnings:             0
requires:
    perl:      5.006
    strict:    0
    warnings:  0
resources:
    repository:  git://github.com/Abigail/App--Bitly.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - Bitly
    - shorten-urls
test_requires:
    LWP::Simple:  0
    strict:       0
    Test::More:   0.88
    warnings:     0
